apiVersion: v1
kind: ServiceAccount # Service Account is used for managing security context constraints policies in Openshift (SCC)
metadata:
  name: twistlock-console
  namespace: {{ .Values.namespace }}
{{- if .Values.CONSOLE_VAULT_AWS_ROLE_ARN }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.CONSOLE_VAULT_AWS_ROLE_ARN }}
{{- end }}